server:
 port: 8766
spring:
 application:
 name: retrieval-service
 cloud:
 gateway.server.webflux:
 discovery:
 ai:
  vectorstore:
    qdrant:
      host: ${QDRANT_HOST:localhost}
      port: ${QDRANT_PORT:6334}
      collection-name: documentos_ia
      api-token: ""
 locator:
 enabled: true
 lower-case-service-id: true
management:
 endpoint:
 health:
 show-details: always
 endpoints:
 web:
 exposure:
 include:
>>>>>>> main:retrieval-service/src/main/resources/application.yaml
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
