server:
  port: 8761

spring:
<<<<<<< HEAD
  application:
    name: naming-server

=======
 application:
 name: naming-server
 cloud:
 gateway.server.webflux:
 discovery:
 locator:
 enabled: true
 lower-case-service-id: true
management:
 endpoint:
 health:
 show-details: always
 endpoints:
 web:
 exposure:
 include:
>>>>>>> main
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
